### ISSUE TITLE
Fase 1: Análisis Exploratorio de Datos(EDA)

### ISSUE THREAD

**Issue by MRocioG** [Adalab/proyecto-da-promo-F-modulo-3-team-6#2]
comprender mejor el conjunto de datos y sus características

**Comment by MRocioG** [comment]
Análisis individual de columnas según numeración del enunciado. Puesta en común en siguiente reunión
Marta	1-10 y 41
Lucia	11-20
Marga	21-30
Rocio	31-40

1. **Age:** La edad del empleado.
2. **Attrition**: Indica si el empleado ha dejado la empresa ("No" significa que no ha dejado la empresa y "Yes" significa que ha dejado la empresa).
3. **BusinessTravel:** Describe la frecuencia de los viajes relacionados con el trabajo del empleado (por ejemplo, "Travel_Rarely" para raramente).
4. **DailyRate:** La tarifa diaria del empleado.
5. **Department:** El departamento en el que trabaja el empleado (por ejemplo, "Research & Development", "Sales", etc.).
6. **DistanceFromHome:** La distancia desde el hogar del empleado hasta su lugar de trabajo.
7. **Education:** Nivel de educación del empleado (generalmente en una escala del 1 al 5).
8. **EducationField**: El campo de educación del empleado.
9. **EmployeeCount**: Un contador que generalmente es 1 y se usa para contar empleados.
10. **EmployeeNumber:** Un número de identificación único para el empleado.
11. **EnvironmentSatisfaction:** Nivel de satisfacción del empleado en relación con su entorno de trabajo. Con valores que estan comprendidos entre el 1 y el 4, siendo el 4 el nivel de máxima satisfacción.
12. **Gender:** El género del empleado. Donde 0 corresponde con "hombre" y 1 con "mujer".
13. **HourlyRate**: La tarifa por hora del empleado.
14. **JobInvolvement**: Nivel de implicación del empleado en su trabajo.
15. **JobLevel**: Nivel jerárquico del empleado en la empresa.
16. **JobRole:** El rol o puesto de trabajo del empleado.
17. **JobSatisfaction:** Nivel de satisfacción del empleado con su trabajo.
18. **MaritalStatus:** El estado civil del empleado (por ejemplo, "Single", "Married", etc.).
19. **MonthlyIncome:** Ingresos mensuales del empleado.
20. **MonthlyRate:** Tasa mensual del empleado.
21. **NumCompaniesWorked:** Número de compañías en las que el empleado ha trabajado.
22. **Over18:** Indica si el empleado es mayor de 18 años.
23. **OverTime:** Indica si el empleado trabaja horas extras ("Yes" para sí o "No" para no).
24. **PercentSalaryHike**: El porcentaje de aumento salarial del empleado.
25. **PerformanceRating**: Calificación de rendimiento del empleado.
26. **RelationshipSatisfaction**: Nivel de satisfacción en las relaciones interpersonales del empleado.
27. **StandardHours**: Las horas estándar de trabajo.
28. **StockOptionLevel**: Nivel de opciones de compra de acciones del empleado.
29. **TotalWorkingYears**: Total de años de experiencia laboral del empleado.
30. **TrainingTimesLastYear**: Número de veces que el empleado recibió capacitación el año pasado.
31. **WorkLifeBalance**: Equilibrio entre trabajo y vida personal del empleado.
32. **YearsAtCompany**: Años que el empleado ha trabajado en la empresa actual.
33. **YearsInCurrentRole**: Años que el empleado ha estado en su puesto actual.
34. **YearsSinceLastPromotion**: Años desde la última promoción del empleado.
35. **YearsWithCurrManager**: Años que el empleado ha estado bajo la supervisión del actual gerente.
36. **SameAsMonthlyIncome**: Ingresos mensuales del empleado.
37. **DateBirth**: Año de nacimiento del empleado (teniendo en cuenta que los datos fueron recogidos en el 2023)
38. **Salary**: Salario de los empleados.
39. **RoleDepartament**: El departamento y el rol del empleado.
40. **NumberChildren**: Número de hijos de los empleados.
41. **RemoteWork**: Si el empleado puede teletrabajar o no.

**Comment by margaobradora** [comment]
el df de todas se llamará df_rawdata
